/*
 * Copyright 2025 Julien Bombled
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace WsusCommander.Properties;

using System.Globalization;
using System.Resources;

/// <summary>
/// A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
public static class Resources
{
    private static ResourceManager? resourceManager;
    private static CultureInfo? resourceCulture;

    /// <summary>
    /// Returns the cached ResourceManager instance used by this class.
    /// </summary>
    public static ResourceManager ResourceManager
    {
        get
        {
            resourceManager ??= new ResourceManager("WsusCommander.Properties.Resources", typeof(Resources).Assembly);
            return resourceManager;
        }
    }

    /// <summary>
    /// Overrides the current thread's CurrentUICulture property for all
    /// resource lookups using this strongly typed resource class.
    /// </summary>
    public static CultureInfo? Culture
    {
        get => resourceCulture;
        set => resourceCulture = value;
    }

    public static string AccessibilityFontScale => ResourceManager.GetString("AccessibilityFontScale", resourceCulture) ?? string.Empty;
    public static string AccessibilityHighContrast => ResourceManager.GetString("AccessibilityHighContrast", resourceCulture) ?? string.Empty;
    public static string AccessibilityNormalContrast => ResourceManager.GetString("AccessibilityNormalContrast", resourceCulture) ?? string.Empty;
    public static string AccessibilityReduceMotion => ResourceManager.GetString("AccessibilityReduceMotion", resourceCulture) ?? string.Empty;
    public static string AppTitle => ResourceManager.GetString("AppTitle", resourceCulture) ?? string.Empty;
    public static string BtnAutoRefresh => ResourceManager.GetString("BtnAutoRefresh", resourceCulture) ?? string.Empty;
    public static string BtnBulkApprove => ResourceManager.GetString("BtnBulkApprove", resourceCulture) ?? string.Empty;
    public static string BtnBulkDecline => ResourceManager.GetString("BtnBulkDecline", resourceCulture) ?? string.Empty;
    public static string BtnCancel => ResourceManager.GetString("BtnCancel", resourceCulture) ?? string.Empty;
    public static string BtnClearFilter => ResourceManager.GetString("BtnClearFilter", resourceCulture) ?? string.Empty;
    public static string BtnConnect => ResourceManager.GetString("BtnConnect", resourceCulture) ?? string.Empty;
    public static string BtnDeleteGroup => ResourceManager.GetString("BtnDeleteGroup", resourceCulture) ?? string.Empty;
    public static string BtnEditGroup => ResourceManager.GetString("BtnEditGroup", resourceCulture) ?? string.Empty;
    public static string BtnExport => ResourceManager.GetString("BtnExport", resourceCulture) ?? string.Empty;
    public static string BtnGenerateReport => ResourceManager.GetString("BtnGenerateReport", resourceCulture) ?? string.Empty;
    public static string BtnNewGroup => ResourceManager.GetString("BtnNewGroup", resourceCulture) ?? string.Empty;
    public static string BtnNo => ResourceManager.GetString("BtnNo", resourceCulture) ?? string.Empty;
    public static string BtnOk => ResourceManager.GetString("BtnOk", resourceCulture) ?? string.Empty;
    public static string BtnRefresh => ResourceManager.GetString("BtnRefresh", resourceCulture) ?? string.Empty;
    public static string BtnStartSync => ResourceManager.GetString("BtnStartSync", resourceCulture) ?? string.Empty;
    public static string BtnViewDetails => ResourceManager.GetString("BtnViewDetails", resourceCulture) ?? string.Empty;
    public static string BtnYes => ResourceManager.GetString("BtnYes", resourceCulture) ?? string.Empty;
    public static string ColApproved => ResourceManager.GetString("ColApproved", resourceCulture) ?? string.Empty;
    public static string ColClassification => ResourceManager.GetString("ColClassification", resourceCulture) ?? string.Empty;
    public static string ColComputerName => ResourceManager.GetString("ColComputerName", resourceCulture) ?? string.Empty;
    public static string ColDate => ResourceManager.GetString("ColDate", resourceCulture) ?? string.Empty;
    public static string ColDaysSinceReport => ResourceManager.GetString("ColDaysSinceReport", resourceCulture) ?? string.Empty;
    public static string ColDeclined => ResourceManager.GetString("ColDeclined", resourceCulture) ?? string.Empty;
    public static string ColFailed => ResourceManager.GetString("ColFailed", resourceCulture) ?? string.Empty;
    public static string ColGroup => ResourceManager.GetString("ColGroup", resourceCulture) ?? string.Empty;
    public static string ColInstalled => ResourceManager.GetString("ColInstalled", resourceCulture) ?? string.Empty;
    public static string ColIpAddress => ResourceManager.GetString("ColIpAddress", resourceCulture) ?? string.Empty;
    public static string ColKB => ResourceManager.GetString("ColKB", resourceCulture) ?? string.Empty;
    public static string ColLastReport => ResourceManager.GetString("ColLastReport", resourceCulture) ?? string.Empty;
    public static string ColNeeded => ResourceManager.GetString("ColNeeded", resourceCulture) ?? string.Empty;
    public static string ColTitle => ResourceManager.GetString("ColTitle", resourceCulture) ?? string.Empty;
    public static string ColTotal => ResourceManager.GetString("ColTotal", resourceCulture) ?? string.Empty;
    public static string ComboSelectGroup => ResourceManager.GetString("ComboSelectGroup", resourceCulture) ?? string.Empty;
    public static string ConfirmApproveUpdate => ResourceManager.GetString("ConfirmApproveUpdate", resourceCulture) ?? string.Empty;
    public static string ConfirmBulkApprove => ResourceManager.GetString("ConfirmBulkApprove", resourceCulture) ?? string.Empty;
    public static string ConfirmBulkDecline => ResourceManager.GetString("ConfirmBulkDecline", resourceCulture) ?? string.Empty;
    public static string ConfirmDeclineUpdate => ResourceManager.GetString("ConfirmDeclineUpdate", resourceCulture) ?? string.Empty;
    public static string ConfirmDeleteGroup => ResourceManager.GetString("ConfirmDeleteGroup", resourceCulture) ?? string.Empty;
    public static string ConfirmStartSync => ResourceManager.GetString("ConfirmStartSync", resourceCulture) ?? string.Empty;
    public static string DialogConfirm => ResourceManager.GetString("DialogConfirm", resourceCulture) ?? string.Empty;
    public static string DialogError => ResourceManager.GetString("DialogError", resourceCulture) ?? string.Empty;
    public static string DialogInfo => ResourceManager.GetString("DialogInfo", resourceCulture) ?? string.Empty;
    public static string DialogWarning => ResourceManager.GetString("DialogWarning", resourceCulture) ?? string.Empty;
    public static string DialogAuthSetupTitle => ResourceManager.GetString("DialogAuthSetupTitle", resourceCulture) ?? string.Empty;
    public static string DialogAuthSetupMessage => ResourceManager.GetString("DialogAuthSetupMessage", resourceCulture) ?? string.Empty;
    public static string DialogAuthSetupFollowup => ResourceManager.GetString("DialogAuthSetupFollowup", resourceCulture) ?? string.Empty;
    public static string BtnLater => ResourceManager.GetString("BtnLater", resourceCulture) ?? string.Empty;
    public static string ErrorCannotDeleteSystemGroup => ResourceManager.GetString("ErrorCannotDeleteSystemGroup", resourceCulture) ?? string.Empty;
    public static string ErrorCircuitBreakerOpen => ResourceManager.GetString("ErrorCircuitBreakerOpen", resourceCulture) ?? string.Empty;
    public static string ErrorConnectionFailed => ResourceManager.GetString("ErrorConnectionFailed", resourceCulture) ?? string.Empty;
    public static string ErrorGroupHasComputers => ResourceManager.GetString("ErrorGroupHasComputers", resourceCulture) ?? string.Empty;
    public static string ErrorNoGroupSelected => ResourceManager.GetString("ErrorNoGroupSelected", resourceCulture) ?? string.Empty;
    public static string ErrorNoReport => ResourceManager.GetString("ErrorNoReport", resourceCulture) ?? string.Empty;
    public static string ErrorNotAuthenticated => ResourceManager.GetString("ErrorNotAuthenticated", resourceCulture) ?? string.Empty;
    public static string ErrorNoUpdateSelected => ResourceManager.GetString("ErrorNoUpdateSelected", resourceCulture) ?? string.Empty;

    public static string ErrorScriptNameRequired => ResourceManager.GetString("ErrorScriptNameRequired", resourceCulture) ?? string.Empty;

    public static string ErrorScriptNameNoPath => ResourceManager.GetString("ErrorScriptNameNoPath", resourceCulture) ?? string.Empty;

    public static string ErrorScriptNameNotPs1 => ResourceManager.GetString("ErrorScriptNameNotPs1", resourceCulture) ?? string.Empty;

    public static string ErrorInvalidPowerShellParameterName => ResourceManager.GetString("ErrorInvalidPowerShellParameterName", resourceCulture) ?? string.Empty;

    public static string ErrorPowerShellParameterNameRequired => ResourceManager.GetString("ErrorPowerShellParameterNameRequired", resourceCulture) ?? string.Empty;
    public static string ErrorClipboardFailed => ResourceManager.GetString("ErrorClipboardFailed", resourceCulture) ?? string.Empty;
    public static string ErrorRetryLimitExceeded => ResourceManager.GetString("ErrorRetryLimitExceeded", resourceCulture) ?? string.Empty;
    public static string ErrorScriptFailed => ResourceManager.GetString("ErrorScriptFailed", resourceCulture) ?? string.Empty;
    public static string ErrorTimeout => ResourceManager.GetString("ErrorTimeout", resourceCulture) ?? string.Empty;
    public static string ErrorUnauthorized => ResourceManager.GetString("ErrorUnauthorized", resourceCulture) ?? string.Empty;
    public static string ExportFormatCsv => ResourceManager.GetString("ExportFormatCsv", resourceCulture) ?? string.Empty;
    public static string ExportFormatJson => ResourceManager.GetString("ExportFormatJson", resourceCulture) ?? string.Empty;
    public static string ExportFormatTsv => ResourceManager.GetString("ExportFormatTsv", resourceCulture) ?? string.Empty;
    public static string ExportFilterCsv => ResourceManager.GetString("ExportFilterCsv", resourceCulture) ?? string.Empty;
    public static string ExportFilterTsv => ResourceManager.GetString("ExportFilterTsv", resourceCulture) ?? string.Empty;
    public static string ExportFilterJson => ResourceManager.GetString("ExportFilterJson", resourceCulture) ?? string.Empty;
    public static string ExportFilterAll => ResourceManager.GetString("ExportFilterAll", resourceCulture) ?? string.Empty;
    public static string ExportHeaderUpdateId => ResourceManager.GetString("ExportHeaderUpdateId", resourceCulture) ?? string.Empty;
    public static string ExportHeaderUpdateTitle => ResourceManager.GetString("ExportHeaderUpdateTitle", resourceCulture) ?? string.Empty;
    public static string ExportHeaderKBArticle => ResourceManager.GetString("ExportHeaderKBArticle", resourceCulture) ?? string.Empty;
    public static string ExportHeaderClassification => ResourceManager.GetString("ExportHeaderClassification", resourceCulture) ?? string.Empty;
    public static string ExportHeaderCreationDate => ResourceManager.GetString("ExportHeaderCreationDate", resourceCulture) ?? string.Empty;
    public static string ExportHeaderApprovalStatus => ResourceManager.GetString("ExportHeaderApprovalStatus", resourceCulture) ?? string.Empty;
    public static string ExportHeaderDeclineStatus => ResourceManager.GetString("ExportHeaderDeclineStatus", resourceCulture) ?? string.Empty;
    public static string ExportHeaderComputerId => ResourceManager.GetString("ExportHeaderComputerId", resourceCulture) ?? string.Empty;
    public static string ExportHeaderComputerName => ResourceManager.GetString("ExportHeaderComputerName", resourceCulture) ?? string.Empty;
    public static string ExportHeaderIpAddress => ResourceManager.GetString("ExportHeaderIpAddress", resourceCulture) ?? string.Empty;
    public static string ExportHeaderGroupName => ResourceManager.GetString("ExportHeaderGroupName", resourceCulture) ?? string.Empty;
    public static string ExportHeaderInstalledCount => ResourceManager.GetString("ExportHeaderInstalledCount", resourceCulture) ?? string.Empty;
    public static string ExportHeaderNeededCount => ResourceManager.GetString("ExportHeaderNeededCount", resourceCulture) ?? string.Empty;
    public static string ExportHeaderFailedCount => ResourceManager.GetString("ExportHeaderFailedCount", resourceCulture) ?? string.Empty;
    public static string ExportHeaderLastContact => ResourceManager.GetString("ExportHeaderLastContact", resourceCulture) ?? string.Empty;
    public static string ExportHeaderGroupId => ResourceManager.GetString("ExportHeaderGroupId", resourceCulture) ?? string.Empty;
    public static string ExportHeaderGroupDescription => ResourceManager.GetString("ExportHeaderGroupDescription", resourceCulture) ?? string.Empty;
    public static string ExportHeaderGroupComputerCount => ResourceManager.GetString("ExportHeaderGroupComputerCount", resourceCulture) ?? string.Empty;
    public static string LogExportingUpdates => ResourceManager.GetString("LogExportingUpdates", resourceCulture) ?? string.Empty;
    public static string LogExportingComputers => ResourceManager.GetString("LogExportingComputers", resourceCulture) ?? string.Empty;
    public static string LogExportingGroups => ResourceManager.GetString("LogExportingGroups", resourceCulture) ?? string.Empty;
    public static string LogExportCompleted => ResourceManager.GetString("LogExportCompleted", resourceCulture) ?? string.Empty;
    public static string FilterAll => ResourceManager.GetString("FilterAll", resourceCulture) ?? string.Empty;
    public static string FilterApproved => ResourceManager.GetString("FilterApproved", resourceCulture) ?? string.Empty;
    public static string FilterCritical => ResourceManager.GetString("FilterCritical", resourceCulture) ?? string.Empty;
    public static string FilterDeclined => ResourceManager.GetString("FilterDeclined", resourceCulture) ?? string.Empty;
    public static string FilterSupersededAll => ResourceManager.GetString("FilterSupersededAll", resourceCulture) ?? string.Empty;
    public static string FilterSupersededOnly => ResourceManager.GetString("FilterSupersededOnly", resourceCulture) ?? string.Empty;
    public static string FilterHideSuperseded => ResourceManager.GetString("FilterHideSuperseded", resourceCulture) ?? string.Empty;
    public static string FilterSecurity => ResourceManager.GetString("FilterSecurity", resourceCulture) ?? string.Empty;
    public static string FilterUnapproved => ResourceManager.GetString("FilterUnapproved", resourceCulture) ?? string.Empty;
    public static string HealthCheckDisk => ResourceManager.GetString("HealthCheckDisk", resourceCulture) ?? string.Empty;
    public static string HealthCheckMemory => ResourceManager.GetString("HealthCheckMemory", resourceCulture) ?? string.Empty;
    public static string HealthCheckPowerShell => ResourceManager.GetString("HealthCheckPowerShell", resourceCulture) ?? string.Empty;
    public static string HealthCheckWsus => ResourceManager.GetString("HealthCheckWsus", resourceCulture) ?? string.Empty;
    public static string HealthStatusDegraded => ResourceManager.GetString("HealthStatusDegraded", resourceCulture) ?? string.Empty;
    public static string HealthStatusHealthy => ResourceManager.GetString("HealthStatusHealthy", resourceCulture) ?? string.Empty;
    public static string HealthStatusUnhealthy => ResourceManager.GetString("HealthStatusUnhealthy", resourceCulture) ?? string.Empty;
    public static string LblComplianceStatus => ResourceManager.GetString("LblComplianceStatus", resourceCulture) ?? string.Empty;
    public static string LblComputerGroups => ResourceManager.GetString("LblComputerGroups", resourceCulture) ?? string.Empty;
    public static string LblCurrentRole => ResourceManager.GetString("LblCurrentRole", resourceCulture) ?? string.Empty;
    public static string LblCurrentUser => ResourceManager.GetString("LblCurrentUser", resourceCulture) ?? string.Empty;
    public static string LblCveIds => ResourceManager.GetString("LblCveIds", resourceCulture) ?? string.Empty;
    public static string LblFileSize => ResourceManager.GetString("LblFileSize", resourceCulture) ?? string.Empty;
    public static string LblFilter => ResourceManager.GetString("LblFilter", resourceCulture) ?? string.Empty;
    public static string LblSupersededFilter => ResourceManager.GetString("LblSupersededFilter", resourceCulture) ?? string.Empty;
    public static string LblGroupDescription => ResourceManager.GetString("LblGroupDescription", resourceCulture) ?? string.Empty;
    public static string LblGroupName => ResourceManager.GetString("LblGroupName", resourceCulture) ?? string.Empty;
    public static string LblHealthStatus => ResourceManager.GetString("LblHealthStatus", resourceCulture) ?? string.Empty;
    public static string LblLastSync => ResourceManager.GetString("LblLastSync", resourceCulture) ?? string.Empty;
    public static string LblParentGroup => ResourceManager.GetString("LblParentGroup", resourceCulture) ?? string.Empty;
    public static string LblProducts => ResourceManager.GetString("LblProducts", resourceCulture) ?? string.Empty;
    public static string LblReleaseDate => ResourceManager.GetString("LblReleaseDate", resourceCulture) ?? string.Empty;
    public static string LblRequiresReboot => ResourceManager.GetString("LblRequiresReboot", resourceCulture) ?? string.Empty;
    public static string LblSearch => ResourceManager.GetString("LblSearch", resourceCulture) ?? string.Empty;
    public static string LblServerName => ResourceManager.GetString("LblServerName", resourceCulture) ?? string.Empty;
    public static string LblServerPort => ResourceManager.GetString("LblServerPort", resourceCulture) ?? string.Empty;
    public static string LblServerVersion => ResourceManager.GetString("LblServerVersion", resourceCulture) ?? string.Empty;
    public static string LblSeverity => ResourceManager.GetString("LblSeverity", resourceCulture) ?? string.Empty;
    public static string LblSuperseded => ResourceManager.GetString("LblSuperseded", resourceCulture) ?? string.Empty;
    public static string LblSupersededBy => ResourceManager.GetString("LblSupersededBy", resourceCulture) ?? string.Empty;
    public static string LblSupersedes => ResourceManager.GetString("LblSupersedes", resourceCulture) ?? string.Empty;
    public static string LblSyncStatus => ResourceManager.GetString("LblSyncStatus", resourceCulture) ?? string.Empty;
    public static string LblUpdateId => ResourceManager.GetString("LblUpdateId", resourceCulture) ?? string.Empty;
    public static string LblUseSsl => ResourceManager.GetString("LblUseSsl", resourceCulture) ?? string.Empty;
    public static string MenuApprove => ResourceManager.GetString("MenuApprove", resourceCulture) ?? string.Empty;
    public static string MenuDecline => ResourceManager.GetString("MenuDecline", resourceCulture) ?? string.Empty;
    public static string MenuMoveToGroup => ResourceManager.GetString("MenuMoveToGroup", resourceCulture) ?? string.Empty;
    public static string MenuRefreshStatus => ResourceManager.GetString("MenuRefreshStatus", resourceCulture) ?? string.Empty;
    public static string MenuViewUpdates => ResourceManager.GetString("MenuViewUpdates", resourceCulture) ?? string.Empty;
    public static string PlaceholderSearch => ResourceManager.GetString("PlaceholderSearch", resourceCulture) ?? string.Empty;
    public static string PlaceholderServerName => ResourceManager.GetString("PlaceholderServerName", resourceCulture) ?? string.Empty;
    public static string ReportCompliance => ResourceManager.GetString("ReportCompliance", resourceCulture) ?? string.Empty;
    public static string ReportCriticalUpdates => ResourceManager.GetString("ReportCriticalUpdates", resourceCulture) ?? string.Empty;
    public static string ReportGenerated => ResourceManager.GetString("ReportGenerated", resourceCulture) ?? string.Empty;
    public static string ReportStaleComputers => ResourceManager.GetString("ReportStaleComputers", resourceCulture) ?? string.Empty;
    public static string RoleAdministrator => ResourceManager.GetString("RoleAdministrator", resourceCulture) ?? string.Empty;
    public static string RoleOperator => ResourceManager.GetString("RoleOperator", resourceCulture) ?? string.Empty;
    public static string RoleViewer => ResourceManager.GetString("RoleViewer", resourceCulture) ?? string.Empty;
    public static string StatusApproved => ResourceManager.GetString("StatusApproved", resourceCulture) ?? string.Empty;
    public static string StatusApproving => ResourceManager.GetString("StatusApproving", resourceCulture) ?? string.Empty;
    public static string StatusAutoRefreshOff => ResourceManager.GetString("StatusAutoRefreshOff", resourceCulture) ?? string.Empty;
    public static string StatusAutoRefreshOn => ResourceManager.GetString("StatusAutoRefreshOn", resourceCulture) ?? string.Empty;
    public static string StatusBulkComplete => ResourceManager.GetString("StatusBulkComplete", resourceCulture) ?? string.Empty;
    public static string StatusBulkOperation => ResourceManager.GetString("StatusBulkOperation", resourceCulture) ?? string.Empty;
    public static string StatusCompliant => ResourceManager.GetString("StatusCompliant", resourceCulture) ?? string.Empty;
    public static string StatusComputersLoaded => ResourceManager.GetString("StatusComputersLoaded", resourceCulture) ?? string.Empty;
    public static string StatusConnected => ResourceManager.GetString("StatusConnected", resourceCulture) ?? string.Empty;
    public static string StatusDeclined => ResourceManager.GetString("StatusDeclined", resourceCulture) ?? string.Empty;
    public static string StatusDeclining => ResourceManager.GetString("StatusDeclining", resourceCulture) ?? string.Empty;
    public static string StatusError => ResourceManager.GetString("StatusError", resourceCulture) ?? string.Empty;
    public static string StatusExportComplete => ResourceManager.GetString("StatusExportComplete", resourceCulture) ?? string.Empty;
    public static string StatusExporting => ResourceManager.GetString("StatusExporting", resourceCulture) ?? string.Empty;
    public static string StatusFiltered => ResourceManager.GetString("StatusFiltered", resourceCulture) ?? string.Empty;
    public static string StatusGeneratingReport => ResourceManager.GetString("StatusGeneratingReport", resourceCulture) ?? string.Empty;
    public static string StatusGroupCreated => ResourceManager.GetString("StatusGroupCreated", resourceCulture) ?? string.Empty;
    public static string StatusGroupDeleted => ResourceManager.GetString("StatusGroupDeleted", resourceCulture) ?? string.Empty;
    public static string StatusLoading => ResourceManager.GetString("StatusLoading", resourceCulture) ?? string.Empty;
    public static string StatusLoadingComputers => ResourceManager.GetString("StatusLoadingComputers", resourceCulture) ?? string.Empty;
    public static string StatusLoadingGroups => ResourceManager.GetString("StatusLoadingGroups", resourceCulture) ?? string.Empty;
    public static string StatusNonCompliant => ResourceManager.GetString("StatusNonCompliant", resourceCulture) ?? string.Empty;
    public static string StatusPartiallyCompliant => ResourceManager.GetString("StatusPartiallyCompliant", resourceCulture) ?? string.Empty;
    public static string StatusReady => ResourceManager.GetString("StatusReady", resourceCulture) ?? string.Empty;
    public static string StatusSyncIdle => ResourceManager.GetString("StatusSyncIdle", resourceCulture) ?? string.Empty;
    public static string StatusSyncing => ResourceManager.GetString("StatusSyncing", resourceCulture) ?? string.Empty;
    public static string StatusSyncStarted => ResourceManager.GetString("StatusSyncStarted", resourceCulture) ?? string.Empty;
    public static string StatusUpdatesLoaded => ResourceManager.GetString("StatusUpdatesLoaded", resourceCulture) ?? string.Empty;
    public static string TabComputers => ResourceManager.GetString("TabComputers", resourceCulture) ?? string.Empty;
    public static string TabGroups => ResourceManager.GetString("TabGroups", resourceCulture) ?? string.Empty;
    public static string TabReports => ResourceManager.GetString("TabReports", resourceCulture) ?? string.Empty;
    public static string TabUpdates => ResourceManager.GetString("TabUpdates", resourceCulture) ?? string.Empty;
    public static string ValidationInvalidFormat => ResourceManager.GetString("ValidationInvalidFormat", resourceCulture) ?? string.Empty;
    public static string ValidationInvalidHostname => ResourceManager.GetString("ValidationInvalidHostname", resourceCulture) ?? string.Empty;
    public static string ValidationInvalidPort => ResourceManager.GetString("ValidationInvalidPort", resourceCulture) ?? string.Empty;
    public static string ValidationMaxLength => ResourceManager.GetString("ValidationMaxLength", resourceCulture) ?? string.Empty;
    public static string ValidationRequired => ResourceManager.GetString("ValidationRequired", resourceCulture) ?? string.Empty;

    // Computer Updates Dialog
    public static string ApprovalApproved => ResourceManager.GetString("ApprovalApproved", resourceCulture) ?? string.Empty;
    public static string ApprovalNotApproved => ResourceManager.GetString("ApprovalNotApproved", resourceCulture) ?? string.Empty;
    public static string BtnApproveSelected => ResourceManager.GetString("BtnApproveSelected", resourceCulture) ?? string.Empty;
    public static string BtnClose => ResourceManager.GetString("BtnClose", resourceCulture) ?? string.Empty;
    public static string BtnDeclineSelected => ResourceManager.GetString("BtnDeclineSelected", resourceCulture) ?? string.Empty;
    public static string ColApprovalStatus => ResourceManager.GetString("ColApprovalStatus", resourceCulture) ?? string.Empty;
    public static string ColStatus => ResourceManager.GetString("ColStatus", resourceCulture) ?? string.Empty;
    public static string ConfirmApproveSelectedUpdates => ResourceManager.GetString("ConfirmApproveSelectedUpdates", resourceCulture) ?? string.Empty;
    public static string ConfirmDeclineSelectedUpdates => ResourceManager.GetString("ConfirmDeclineSelectedUpdates", resourceCulture) ?? string.Empty;
    public static string DialogComputerUpdates => ResourceManager.GetString("DialogComputerUpdates", resourceCulture) ?? string.Empty;
    public static string FilterFailed => ResourceManager.GetString("FilterFailed", resourceCulture) ?? string.Empty;
    public static string FilterNeeded => ResourceManager.GetString("FilterNeeded", resourceCulture) ?? string.Empty;
    public static string FilterNotApproved => ResourceManager.GetString("FilterNotApproved", resourceCulture) ?? string.Empty;
    public static string LblSupersededInfo => ResourceManager.GetString("LblSupersededInfo", resourceCulture) ?? string.Empty;
    public static string StatusDownloaded => ResourceManager.GetString("StatusDownloaded", resourceCulture) ?? string.Empty;
    public static string StatusFailed => ResourceManager.GetString("StatusFailed", resourceCulture) ?? string.Empty;
    public static string StatusInstalled => ResourceManager.GetString("StatusInstalled", resourceCulture) ?? string.Empty;
    public static string StatusLoadingUpdates => ResourceManager.GetString("StatusLoadingUpdates", resourceCulture) ?? string.Empty;
    public static string StatusNotApplicable => ResourceManager.GetString("StatusNotApplicable", resourceCulture) ?? string.Empty;
    public static string StatusNotInstalled => ResourceManager.GetString("StatusNotInstalled", resourceCulture) ?? string.Empty;
    public static string StatusPendingReboot => ResourceManager.GetString("StatusPendingReboot", resourceCulture) ?? string.Empty;
    public static string StatusUpdatesLoadedForComputer => ResourceManager.GetString("StatusUpdatesLoadedForComputer", resourceCulture) ?? string.Empty;
    public static string TipNotApproved => ResourceManager.GetString("TipNotApproved", resourceCulture) ?? string.Empty;
    public static string TipSuperseded => ResourceManager.GetString("TipSuperseded", resourceCulture) ?? string.Empty;

    // One-Click Actions
    public static string BtnDeclineSuperseded => ResourceManager.GetString("BtnDeclineSuperseded", resourceCulture) ?? string.Empty;
    public static string BtnApproveCritical => ResourceManager.GetString("BtnApproveCritical", resourceCulture) ?? string.Empty;
    public static string BtnApproveSecurity => ResourceManager.GetString("BtnApproveSecurity", resourceCulture) ?? string.Empty;
    public static string ConfirmDeclineSuperseded => ResourceManager.GetString("ConfirmDeclineSuperseded", resourceCulture) ?? string.Empty;
    public static string ConfirmApproveCritical => ResourceManager.GetString("ConfirmApproveCritical", resourceCulture) ?? string.Empty;
    public static string ConfirmApproveSecurity => ResourceManager.GetString("ConfirmApproveSecurity", resourceCulture) ?? string.Empty;
    public static string StatusDecliningSuperseded => ResourceManager.GetString("StatusDecliningSuperseded", resourceCulture) ?? string.Empty;
    public static string StatusApprovingCritical => ResourceManager.GetString("StatusApprovingCritical", resourceCulture) ?? string.Empty;
    public static string StatusApprovingSecurity => ResourceManager.GetString("StatusApprovingSecurity", resourceCulture) ?? string.Empty;
    public static string StatusDeclinedSuperseded => ResourceManager.GetString("StatusDeclinedSuperseded", resourceCulture) ?? string.Empty;
    public static string StatusApprovedCritical => ResourceManager.GetString("StatusApprovedCritical", resourceCulture) ?? string.Empty;
    public static string StatusApprovedSecurity => ResourceManager.GetString("StatusApprovedSecurity", resourceCulture) ?? string.Empty;
    public static string ErrorNoSupersededUpdates => ResourceManager.GetString("ErrorNoSupersededUpdates", resourceCulture) ?? string.Empty;
    public static string ErrorNoCriticalUpdates => ResourceManager.GetString("ErrorNoCriticalUpdates", resourceCulture) ?? string.Empty;
    public static string ErrorNoSecurityUpdates => ResourceManager.GetString("ErrorNoSecurityUpdates", resourceCulture) ?? string.Empty;
    public static string LblQuickActions => ResourceManager.GetString("LblQuickActions", resourceCulture) ?? string.Empty;

    // Dashboard
    public static string TabDashboard => ResourceManager.GetString("TabDashboard", resourceCulture) ?? string.Empty;
    public static string DashboardTitle => ResourceManager.GetString("DashboardTitle", resourceCulture) ?? string.Empty;
    public static string DashboardTotalUpdates => ResourceManager.GetString("DashboardTotalUpdates", resourceCulture) ?? string.Empty;
    public static string DashboardUnapproved => ResourceManager.GetString("DashboardUnapproved", resourceCulture) ?? string.Empty;
    public static string DashboardSuperseded => ResourceManager.GetString("DashboardSuperseded", resourceCulture) ?? string.Empty;
    public static string DashboardCriticalPending => ResourceManager.GetString("DashboardCriticalPending", resourceCulture) ?? string.Empty;
    public static string DashboardSecurityPending => ResourceManager.GetString("DashboardSecurityPending", resourceCulture) ?? string.Empty;
    public static string DashboardTotalComputers => ResourceManager.GetString("DashboardTotalComputers", resourceCulture) ?? string.Empty;
    public static string DashboardNeedingUpdates => ResourceManager.GetString("DashboardNeedingUpdates", resourceCulture) ?? string.Empty;
    public static string DashboardUpToDate => ResourceManager.GetString("DashboardUpToDate", resourceCulture) ?? string.Empty;
    public static string DashboardCompliance => ResourceManager.GetString("DashboardCompliance", resourceCulture) ?? string.Empty;
    public static string DashboardLastSync => ResourceManager.GetString("DashboardLastSync", resourceCulture) ?? string.Empty;
    public static string DashboardUpdateStats => ResourceManager.GetString("DashboardUpdateStats", resourceCulture) ?? string.Empty;
    public static string DashboardComputerStats => ResourceManager.GetString("DashboardComputerStats", resourceCulture) ?? string.Empty;
    public static string DashboardQuickActions => ResourceManager.GetString("DashboardQuickActions", resourceCulture) ?? string.Empty;
    public static string DashboardActionRequired => ResourceManager.GetString("DashboardActionRequired", resourceCulture) ?? string.Empty;
    public static string DashboardNoActionRequired => ResourceManager.GetString("DashboardNoActionRequired", resourceCulture) ?? string.Empty;
    public static string DashboardOperationalInsights => ResourceManager.GetString("DashboardOperationalInsights", resourceCulture) ?? string.Empty;
    public static string DashboardSecurityAccess => ResourceManager.GetString("DashboardSecurityAccess", resourceCulture) ?? string.Empty;
    public static string DashboardSyncAge => ResourceManager.GetString("DashboardSyncAge", resourceCulture) ?? string.Empty;
    public static string DashboardHealth => ResourceManager.GetString("DashboardHealth", resourceCulture) ?? string.Empty;
    public static string DashboardAutoRefresh => ResourceManager.GetString("DashboardAutoRefresh", resourceCulture) ?? string.Empty;
    public static string DashboardUserRole => ResourceManager.GetString("DashboardUserRole", resourceCulture) ?? string.Empty;
    public static string DashboardAuthenticationRequired => ResourceManager.GetString("DashboardAuthenticationRequired", resourceCulture) ?? string.Empty;
    public static string DashboardApprovalConfirmation => ResourceManager.GetString("DashboardApprovalConfirmation", resourceCulture) ?? string.Empty;
    public static string DashboardDeclineConfirmation => ResourceManager.GetString("DashboardDeclineConfirmation", resourceCulture) ?? string.Empty;
    public static string DashboardSyncConfirmation => ResourceManager.GetString("DashboardSyncConfirmation", resourceCulture) ?? string.Empty;
    public static string DashboardAuditLogging => ResourceManager.GetString("DashboardAuditLogging", resourceCulture) ?? string.Empty;
    public static string DashboardSslStatus => ResourceManager.GetString("DashboardSslStatus", resourceCulture) ?? string.Empty;
    public static string DashboardCertificateValidation => ResourceManager.GetString("DashboardCertificateValidation", resourceCulture) ?? string.Empty;
    public static string DashboardLastSyncNever => ResourceManager.GetString("DashboardLastSyncNever", resourceCulture) ?? string.Empty;
    public static string DashboardSyncAgeUnknown => ResourceManager.GetString("DashboardSyncAgeUnknown", resourceCulture) ?? string.Empty;
    public static string DashboardAutoRefreshEnabled => ResourceManager.GetString("DashboardAutoRefreshEnabled", resourceCulture) ?? string.Empty;
    public static string DashboardAutoRefreshDisabled => ResourceManager.GetString("DashboardAutoRefreshDisabled", resourceCulture) ?? string.Empty;
    public static string DashboardPendingLabel => ResourceManager.GetString("DashboardPendingLabel", resourceCulture) ?? string.Empty;
    public static string DashboardReadyLabel => ResourceManager.GetString("DashboardReadyLabel", resourceCulture) ?? string.Empty;
    public static string DashboardHealthUnknown => ResourceManager.GetString("DashboardHealthUnknown", resourceCulture) ?? string.Empty;
    public static string DashboardUserUnknown => ResourceManager.GetString("DashboardUserUnknown", resourceCulture) ?? string.Empty;
    public static string DashboardActionReviewUpdates => ResourceManager.GetString("DashboardActionReviewUpdates", resourceCulture) ?? string.Empty;
    public static string DashboardActionReviewSuperseded => ResourceManager.GetString("DashboardActionReviewSuperseded", resourceCulture) ?? string.Empty;
    public static string DashboardActionStartSync => ResourceManager.GetString("DashboardActionStartSync", resourceCulture) ?? string.Empty;
    public static string DashboardActionOpenReports => ResourceManager.GetString("DashboardActionOpenReports", resourceCulture) ?? string.Empty;
    public static string StatusEnabled => ResourceManager.GetString("StatusEnabled", resourceCulture) ?? string.Empty;
    public static string StatusDisabled => ResourceManager.GetString("StatusDisabled", resourceCulture) ?? string.Empty;

    // Filter Presets
    public static string PresetAllUpdates => ResourceManager.GetString("PresetAllUpdates", resourceCulture) ?? string.Empty;
    public static string PresetUnapprovedOnly => ResourceManager.GetString("PresetUnapprovedOnly", resourceCulture) ?? string.Empty;
    public static string PresetCriticalUpdates => ResourceManager.GetString("PresetCriticalUpdates", resourceCulture) ?? string.Empty;
    public static string PresetSecurityUpdates => ResourceManager.GetString("PresetSecurityUpdates", resourceCulture) ?? string.Empty;
    public static string PresetDeclinedUpdates => ResourceManager.GetString("PresetDeclinedUpdates", resourceCulture) ?? string.Empty;
    public static string LblFilterPresets => ResourceManager.GetString("LblFilterPresets", resourceCulture) ?? string.Empty;
    public static string BtnSavePreset => ResourceManager.GetString("BtnSavePreset", resourceCulture) ?? string.Empty;
    public static string BtnDeletePreset => ResourceManager.GetString("BtnDeletePreset", resourceCulture) ?? string.Empty;
    public static string DialogSavePreset => ResourceManager.GetString("DialogSavePreset", resourceCulture) ?? string.Empty;
    public static string LblPresetName => ResourceManager.GetString("LblPresetName", resourceCulture) ?? string.Empty;
    public static string StatusPresetSaved => ResourceManager.GetString("StatusPresetSaved", resourceCulture) ?? string.Empty;
    public static string StatusPresetDeleted => ResourceManager.GetString("StatusPresetDeleted", resourceCulture) ?? string.Empty;
    public static string ErrorCannotDeleteBuiltIn => ResourceManager.GetString("ErrorCannotDeleteBuiltIn", resourceCulture) ?? string.Empty;

    // Pagination
    public static string StatusPagination => ResourceManager.GetString("StatusPagination", resourceCulture) ?? string.Empty;
    public static string LblPageSize => ResourceManager.GetString("LblPageSize", resourceCulture) ?? string.Empty;
    public static string BtnFirstPage => ResourceManager.GetString("BtnFirstPage", resourceCulture) ?? string.Empty;
    public static string BtnPreviousPage => ResourceManager.GetString("BtnPreviousPage", resourceCulture) ?? string.Empty;
    public static string BtnNextPage => ResourceManager.GetString("BtnNextPage", resourceCulture) ?? string.Empty;
    public static string BtnLastPage => ResourceManager.GetString("BtnLastPage", resourceCulture) ?? string.Empty;

    // Activity Monitor
    public static string TabActivity => ResourceManager.GetString("TabActivity", resourceCulture) ?? string.Empty;
    public static string ColTimestamp => ResourceManager.GetString("ColTimestamp", resourceCulture) ?? string.Empty;
    public static string ColActivityType => ResourceManager.GetString("ColActivityType", resourceCulture) ?? string.Empty;
    public static string ColDescription => ResourceManager.GetString("ColDescription", resourceCulture) ?? string.Empty;
    public static string ColUser => ResourceManager.GetString("ColUser", resourceCulture) ?? string.Empty;
    public static string ColTarget => ResourceManager.GetString("ColTarget", resourceCulture) ?? string.Empty;
    public static string StatusLoadingActivity => ResourceManager.GetString("StatusLoadingActivity", resourceCulture) ?? string.Empty;
    public static string StatusActivityLoaded => ResourceManager.GetString("StatusActivityLoaded", resourceCulture) ?? string.Empty;
    public static string ActivityApproval => ResourceManager.GetString("ActivityApproval", resourceCulture) ?? string.Empty;
    public static string ActivityDecline => ResourceManager.GetString("ActivityDecline", resourceCulture) ?? string.Empty;
    public static string ActivitySync => ResourceManager.GetString("ActivitySync", resourceCulture) ?? string.Empty;
    public static string ActivityDownload => ResourceManager.GetString("ActivityDownload", resourceCulture) ?? string.Empty;

    // Charts and Visualizations
    public static string DashboardUpdateDistribution => ResourceManager.GetString("DashboardUpdateDistribution", resourceCulture) ?? string.Empty;

    // Approval Rules
    public static string TabRules => ResourceManager.GetString("TabRules", resourceCulture) ?? string.Empty;
    public static string BtnNewRule => ResourceManager.GetString("BtnNewRule", resourceCulture) ?? string.Empty;
    public static string BtnEditRule => ResourceManager.GetString("BtnEditRule", resourceCulture) ?? string.Empty;
    public static string BtnDeleteRule => ResourceManager.GetString("BtnDeleteRule", resourceCulture) ?? string.Empty;
    public static string BtnApplyRules => ResourceManager.GetString("BtnApplyRules", resourceCulture) ?? string.Empty;
    public static string ColRuleName => ResourceManager.GetString("ColRuleName", resourceCulture) ?? string.Empty;
    public static string ColCondition => ResourceManager.GetString("ColCondition", resourceCulture) ?? string.Empty;
    public static string ColAction => ResourceManager.GetString("ColAction", resourceCulture) ?? string.Empty;
    public static string ColEnabled => ResourceManager.GetString("ColEnabled", resourceCulture) ?? string.Empty;
    public static string ColPriority => ResourceManager.GetString("ColPriority", resourceCulture) ?? string.Empty;
    public static string DialogNewRule => ResourceManager.GetString("DialogNewRule", resourceCulture) ?? string.Empty;
    public static string DialogEditRule => ResourceManager.GetString("DialogEditRule", resourceCulture) ?? string.Empty;
    public static string LblRuleName => ResourceManager.GetString("LblRuleName", resourceCulture) ?? string.Empty;
    public static string LblConditionType => ResourceManager.GetString("LblConditionType", resourceCulture) ?? string.Empty;
    public static string LblConditionValue => ResourceManager.GetString("LblConditionValue", resourceCulture) ?? string.Empty;
    public static string LblRuleAction => ResourceManager.GetString("LblRuleAction", resourceCulture) ?? string.Empty;
    public static string LblTargetGroup => ResourceManager.GetString("LblTargetGroup", resourceCulture) ?? string.Empty;
    public static string LblPriority => ResourceManager.GetString("LblPriority", resourceCulture) ?? string.Empty;
    public static string ConditionClassification => ResourceManager.GetString("ConditionClassification", resourceCulture) ?? string.Empty;
    public static string ConditionSuperseded => ResourceManager.GetString("ConditionSuperseded", resourceCulture) ?? string.Empty;
    public static string ConditionTitleContains => ResourceManager.GetString("ConditionTitleContains", resourceCulture) ?? string.Empty;
    public static string ConditionKbArticle => ResourceManager.GetString("ConditionKbArticle", resourceCulture) ?? string.Empty;
    public static string ActionApprove => ResourceManager.GetString("ActionApprove", resourceCulture) ?? string.Empty;
    public static string ActionDecline => ResourceManager.GetString("ActionDecline", resourceCulture) ?? string.Empty;
    public static string StatusRuleSaved => ResourceManager.GetString("StatusRuleSaved", resourceCulture) ?? string.Empty;
    public static string StatusRuleDeleted => ResourceManager.GetString("StatusRuleDeleted", resourceCulture) ?? string.Empty;
    public static string StatusApplyingRules => ResourceManager.GetString("StatusApplyingRules", resourceCulture) ?? string.Empty;
    public static string StatusRulesApplied => ResourceManager.GetString("StatusRulesApplied", resourceCulture) ?? string.Empty;
    public static string ConfirmDeleteRule => ResourceManager.GetString("ConfirmDeleteRule", resourceCulture) ?? string.Empty;
    public static string RulesDescription => ResourceManager.GetString("RulesDescription", resourceCulture) ?? string.Empty;
    public static string TooltipRefresh => ResourceManager.GetString("TooltipRefresh", resourceCulture) ?? string.Empty;
    public static string TooltipStartSync => ResourceManager.GetString("TooltipStartSync", resourceCulture) ?? string.Empty;
    public static string TooltipExport => ResourceManager.GetString("TooltipExport", resourceCulture) ?? string.Empty;
    public static string TooltipDisconnect => ResourceManager.GetString("TooltipDisconnect", resourceCulture) ?? string.Empty;
    public static string TooltipApprove => ResourceManager.GetString("TooltipApprove", resourceCulture) ?? string.Empty;
    public static string TooltipDecline => ResourceManager.GetString("TooltipDecline", resourceCulture) ?? string.Empty;
    public static string TooltipSearch => ResourceManager.GetString("TooltipSearch", resourceCulture) ?? string.Empty;
    public static string StatusBarHealthHealthy => ResourceManager.GetString("StatusBarHealthHealthy", resourceCulture) ?? string.Empty;
    public static string StatusBarHealthWarning => ResourceManager.GetString("StatusBarHealthWarning", resourceCulture) ?? string.Empty;
    public static string StatusBarHealthCritical => ResourceManager.GetString("StatusBarHealthCritical", resourceCulture) ?? string.Empty;
    public static string ConfirmDisconnect => ResourceManager.GetString("ConfirmDisconnect", resourceCulture) ?? string.Empty;
    public static string StatusDisconnected => ResourceManager.GetString("StatusDisconnected", resourceCulture) ?? string.Empty;
    public static string ThemeLight => ResourceManager.GetString("ThemeLight", resourceCulture) ?? string.Empty;
    public static string ThemeDark => ResourceManager.GetString("ThemeDark", resourceCulture) ?? string.Empty;
    public static string ThemeSystem => ResourceManager.GetString("ThemeSystem", resourceCulture) ?? string.Empty;
    public static string TooltipTheme => ResourceManager.GetString("TooltipTheme", resourceCulture) ?? string.Empty;
    public static string ConfirmDeclineSupersededCount => ResourceManager.GetString("ConfirmDeclineSupersededCount", resourceCulture) ?? string.Empty;
    public static string ConfirmApproveCount => ResourceManager.GetString("ConfirmApproveCount", resourceCulture) ?? string.Empty;
    public static string StatusCountingUpdates => ResourceManager.GetString("StatusCountingUpdates", resourceCulture) ?? string.Empty;
    public static string ProgressApprovingCount => ResourceManager.GetString("ProgressApprovingCount", resourceCulture) ?? string.Empty;
    public static string ProgressDecliningCount => ResourceManager.GetString("ProgressDecliningCount", resourceCulture) ?? string.Empty;
    public static string MenuCopyKB => ResourceManager.GetString("MenuCopyKB", resourceCulture) ?? string.Empty;
    public static string MenuSearchKB => ResourceManager.GetString("MenuSearchKB", resourceCulture) ?? string.Empty;
    public static string ToastApproveSuccess => ResourceManager.GetString("ToastApproveSuccess", resourceCulture) ?? string.Empty;
    public static string ToastDeclineSuccess => ResourceManager.GetString("ToastDeclineSuccess", resourceCulture) ?? string.Empty;
    public static string ToastSyncComplete => ResourceManager.GetString("ToastSyncComplete", resourceCulture) ?? string.Empty;
    public static string GridUpdates => ResourceManager.GetString("GridUpdates", resourceCulture) ?? string.Empty;
    public static string GridComputers => ResourceManager.GetString("GridComputers", resourceCulture) ?? string.Empty;
    public static string GridActivityLog => ResourceManager.GetString("GridActivityLog", resourceCulture) ?? string.Empty;
    public static string GridApprovalRules => ResourceManager.GetString("GridApprovalRules", resourceCulture) ?? string.Empty;
    public static string HealthStatusUnknown => ResourceManager.GetString("HealthStatusUnknown", resourceCulture) ?? string.Empty;
    public static string TooltipHealthIndicator => ResourceManager.GetString("TooltipHealthIndicator", resourceCulture) ?? string.Empty;
    public static string StatusCopied => ResourceManager.GetString("StatusCopied", resourceCulture) ?? string.Empty;
    public static string TooltipRefreshShortcut => ResourceManager.GetString("TooltipRefreshShortcut", resourceCulture) ?? string.Empty;
    public static string TooltipSyncShortcut => ResourceManager.GetString("TooltipSyncShortcut", resourceCulture) ?? string.Empty;
    public static string TooltipApproveShortcut => ResourceManager.GetString("TooltipApproveShortcut", resourceCulture) ?? string.Empty;
    public static string TooltipDeclineShortcut => ResourceManager.GetString("TooltipDeclineShortcut", resourceCulture) ?? string.Empty;
    public static string TooltipExportShortcut => ResourceManager.GetString("TooltipExportShortcut", resourceCulture) ?? string.Empty;
    public static string BtnDismiss => ResourceManager.GetString("BtnDismiss", resourceCulture) ?? string.Empty;
}
