//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace WsusCommander.Properties;

/// <summary>
/// A strongly-typed resource class for looking up localized strings.
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public class Resources
{
    private static global::System.Resources.ResourceManager? resourceMan;
    private static global::System.Globalization.CultureInfo? resourceCulture;

    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Resources() { }

    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Resources.ResourceManager ResourceManager
    {
        get
        {
            if (resourceMan is null)
            {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WsusCommander.Properties.Resources", typeof(Resources).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }

    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Globalization.CultureInfo? Culture
    {
        get { return resourceCulture; }
        set { resourceCulture = value; }
    }

    public static string AppTitle => ResourceManager.GetString("AppTitle", resourceCulture) ?? string.Empty;
    public static string BtnConnect => ResourceManager.GetString("BtnConnect", resourceCulture) ?? string.Empty;
    public static string StatusReady => ResourceManager.GetString("StatusReady", resourceCulture) ?? string.Empty;
    public static string StatusConnected => ResourceManager.GetString("StatusConnected", resourceCulture) ?? string.Empty;
    public static string StatusError => ResourceManager.GetString("StatusError", resourceCulture) ?? string.Empty;
    public static string LblServerVersion => ResourceManager.GetString("LblServerVersion", resourceCulture) ?? string.Empty;
    public static string ColTitle => ResourceManager.GetString("ColTitle", resourceCulture) ?? string.Empty;
    public static string ColKB => ResourceManager.GetString("ColKB", resourceCulture) ?? string.Empty;
    public static string ColClassification => ResourceManager.GetString("ColClassification", resourceCulture) ?? string.Empty;
    public static string ColDate => ResourceManager.GetString("ColDate", resourceCulture) ?? string.Empty;
    public static string ColApproved => ResourceManager.GetString("ColApproved", resourceCulture) ?? string.Empty;
    public static string BtnRefresh => ResourceManager.GetString("BtnRefresh", resourceCulture) ?? string.Empty;
    public static string StatusLoading => ResourceManager.GetString("StatusLoading", resourceCulture) ?? string.Empty;
    public static string StatusUpdatesLoaded => ResourceManager.GetString("StatusUpdatesLoaded", resourceCulture) ?? string.Empty;
    public static string MenuApprove => ResourceManager.GetString("MenuApprove", resourceCulture) ?? string.Empty;
    public static string MenuDecline => ResourceManager.GetString("MenuDecline", resourceCulture) ?? string.Empty;
    public static string StatusApproved => ResourceManager.GetString("StatusApproved", resourceCulture) ?? string.Empty;
    public static string StatusDeclined => ResourceManager.GetString("StatusDeclined", resourceCulture) ?? string.Empty;
    public static string StatusApproving => ResourceManager.GetString("StatusApproving", resourceCulture) ?? string.Empty;
    public static string StatusDeclining => ResourceManager.GetString("StatusDeclining", resourceCulture) ?? string.Empty;
    public static string LblComputerGroups => ResourceManager.GetString("LblComputerGroups", resourceCulture) ?? string.Empty;
    public static string ComboSelectGroup => ResourceManager.GetString("ComboSelectGroup", resourceCulture) ?? string.Empty;
    public static string LblSyncStatus => ResourceManager.GetString("LblSyncStatus", resourceCulture) ?? string.Empty;
    public static string LblLastSync => ResourceManager.GetString("LblLastSync", resourceCulture) ?? string.Empty;
    public static string BtnStartSync => ResourceManager.GetString("BtnStartSync", resourceCulture) ?? string.Empty;
    public static string StatusSyncing => ResourceManager.GetString("StatusSyncing", resourceCulture) ?? string.Empty;
    public static string StatusSyncStarted => ResourceManager.GetString("StatusSyncStarted", resourceCulture) ?? string.Empty;
    public static string StatusSyncIdle => ResourceManager.GetString("StatusSyncIdle", resourceCulture) ?? string.Empty;
    public static string TabUpdates => ResourceManager.GetString("TabUpdates", resourceCulture) ?? string.Empty;
    public static string TabComputers => ResourceManager.GetString("TabComputers", resourceCulture) ?? string.Empty;
    public static string ColComputerName => ResourceManager.GetString("ColComputerName", resourceCulture) ?? string.Empty;
    public static string ColIpAddress => ResourceManager.GetString("ColIpAddress", resourceCulture) ?? string.Empty;
    public static string ColInstalled => ResourceManager.GetString("ColInstalled", resourceCulture) ?? string.Empty;
    public static string ColNeeded => ResourceManager.GetString("ColNeeded", resourceCulture) ?? string.Empty;
    public static string ColFailed => ResourceManager.GetString("ColFailed", resourceCulture) ?? string.Empty;
    public static string ColLastReport => ResourceManager.GetString("ColLastReport", resourceCulture) ?? string.Empty;
    public static string ColGroup => ResourceManager.GetString("ColGroup", resourceCulture) ?? string.Empty;
    public static string ColTotal => ResourceManager.GetString("ColTotal", resourceCulture) ?? string.Empty;
    public static string BtnAutoRefresh => ResourceManager.GetString("BtnAutoRefresh", resourceCulture) ?? string.Empty;
    public static string StatusAutoRefreshOn => ResourceManager.GetString("StatusAutoRefreshOn", resourceCulture) ?? string.Empty;
    public static string StatusAutoRefreshOff => ResourceManager.GetString("StatusAutoRefreshOff", resourceCulture) ?? string.Empty;
    public static string ColDeclined => ResourceManager.GetString("ColDeclined", resourceCulture) ?? string.Empty;
    public static string StatusLoadingGroups => ResourceManager.GetString("StatusLoadingGroups", resourceCulture) ?? string.Empty;
    public static string StatusLoadingComputers => ResourceManager.GetString("StatusLoadingComputers", resourceCulture) ?? string.Empty;
    public static string StatusComputersLoaded => ResourceManager.GetString("StatusComputersLoaded", resourceCulture) ?? string.Empty;
    public static string ErrorNoGroupSelected => ResourceManager.GetString("ErrorNoGroupSelected", resourceCulture) ?? string.Empty;
    public static string ErrorNoUpdateSelected => ResourceManager.GetString("ErrorNoUpdateSelected", resourceCulture) ?? string.Empty;
    public static string BtnBulkApprove => ResourceManager.GetString("BtnBulkApprove", resourceCulture) ?? string.Empty;
    public static string BtnBulkDecline => ResourceManager.GetString("BtnBulkDecline", resourceCulture) ?? string.Empty;
    public static string StatusBulkOperation => ResourceManager.GetString("StatusBulkOperation", resourceCulture) ?? string.Empty;
    public static string StatusBulkComplete => ResourceManager.GetString("StatusBulkComplete", resourceCulture) ?? string.Empty;
    public static string ConfirmBulkApprove => ResourceManager.GetString("ConfirmBulkApprove", resourceCulture) ?? string.Empty;
    public static string ConfirmBulkDecline => ResourceManager.GetString("ConfirmBulkDecline", resourceCulture) ?? string.Empty;
    public static string BtnExport => ResourceManager.GetString("BtnExport", resourceCulture) ?? string.Empty;
    public static string ExportFormatCsv => ResourceManager.GetString("ExportFormatCsv", resourceCulture) ?? string.Empty;
    public static string ExportFormatTsv => ResourceManager.GetString("ExportFormatTsv", resourceCulture) ?? string.Empty;
    public static string ExportFormatJson => ResourceManager.GetString("ExportFormatJson", resourceCulture) ?? string.Empty;
    public static string StatusExporting => ResourceManager.GetString("StatusExporting", resourceCulture) ?? string.Empty;
    public static string StatusExportComplete => ResourceManager.GetString("StatusExportComplete", resourceCulture) ?? string.Empty;
    public static string HealthStatusHealthy => ResourceManager.GetString("HealthStatusHealthy", resourceCulture) ?? string.Empty;
    public static string HealthStatusDegraded => ResourceManager.GetString("HealthStatusDegraded", resourceCulture) ?? string.Empty;
    public static string HealthStatusUnhealthy => ResourceManager.GetString("HealthStatusUnhealthy", resourceCulture) ?? string.Empty;
    public static string LblHealthStatus => ResourceManager.GetString("LblHealthStatus", resourceCulture) ?? string.Empty;
    public static string HealthCheckWsus => ResourceManager.GetString("HealthCheckWsus", resourceCulture) ?? string.Empty;
    public static string HealthCheckPowerShell => ResourceManager.GetString("HealthCheckPowerShell", resourceCulture) ?? string.Empty;
    public static string HealthCheckDisk => ResourceManager.GetString("HealthCheckDisk", resourceCulture) ?? string.Empty;
    public static string HealthCheckMemory => ResourceManager.GetString("HealthCheckMemory", resourceCulture) ?? string.Empty;
    public static string LblSearch => ResourceManager.GetString("LblSearch", resourceCulture) ?? string.Empty;
    public static string PlaceholderSearch => ResourceManager.GetString("PlaceholderSearch", resourceCulture) ?? string.Empty;
    public static string LblFilter => ResourceManager.GetString("LblFilter", resourceCulture) ?? string.Empty;
    public static string FilterAll => ResourceManager.GetString("FilterAll", resourceCulture) ?? string.Empty;
    public static string FilterApproved => ResourceManager.GetString("FilterApproved", resourceCulture) ?? string.Empty;
    public static string FilterUnapproved => ResourceManager.GetString("FilterUnapproved", resourceCulture) ?? string.Empty;
    public static string FilterDeclined => ResourceManager.GetString("FilterDeclined", resourceCulture) ?? string.Empty;
    public static string FilterCritical => ResourceManager.GetString("FilterCritical", resourceCulture) ?? string.Empty;
    public static string FilterSecurity => ResourceManager.GetString("FilterSecurity", resourceCulture) ?? string.Empty;
    public static string BtnClearFilter => ResourceManager.GetString("BtnClearFilter", resourceCulture) ?? string.Empty;
    public static string StatusFiltered => ResourceManager.GetString("StatusFiltered", resourceCulture) ?? string.Empty;
    public static string TabReports => ResourceManager.GetString("TabReports", resourceCulture) ?? string.Empty;
    public static string ReportCompliance => ResourceManager.GetString("ReportCompliance", resourceCulture) ?? string.Empty;
    public static string ReportStaleComputers => ResourceManager.GetString("ReportStaleComputers", resourceCulture) ?? string.Empty;
    public static string ReportCriticalUpdates => ResourceManager.GetString("ReportCriticalUpdates", resourceCulture) ?? string.Empty;
    public static string LblComplianceStatus => ResourceManager.GetString("LblComplianceStatus", resourceCulture) ?? string.Empty;
    public static string StatusCompliant => ResourceManager.GetString("StatusCompliant", resourceCulture) ?? string.Empty;
    public static string StatusPartiallyCompliant => ResourceManager.GetString("StatusPartiallyCompliant", resourceCulture) ?? string.Empty;
    public static string StatusNonCompliant => ResourceManager.GetString("StatusNonCompliant", resourceCulture) ?? string.Empty;
    public static string BtnGenerateReport => ResourceManager.GetString("BtnGenerateReport", resourceCulture) ?? string.Empty;
    public static string StatusGeneratingReport => ResourceManager.GetString("StatusGeneratingReport", resourceCulture) ?? string.Empty;
    public static string ReportGenerated => ResourceManager.GetString("ReportGenerated", resourceCulture) ?? string.Empty;
    public static string ErrorNoReport => ResourceManager.GetString("ErrorNoReport", resourceCulture) ?? string.Empty;
    public static string ColDaysSinceReport => ResourceManager.GetString("ColDaysSinceReport", resourceCulture) ?? string.Empty;
    public static string TabGroups => ResourceManager.GetString("TabGroups", resourceCulture) ?? string.Empty;
    public static string BtnNewGroup => ResourceManager.GetString("BtnNewGroup", resourceCulture) ?? string.Empty;
    public static string BtnEditGroup => ResourceManager.GetString("BtnEditGroup", resourceCulture) ?? string.Empty;
    public static string BtnDeleteGroup => ResourceManager.GetString("BtnDeleteGroup", resourceCulture) ?? string.Empty;
    public static string LblGroupName => ResourceManager.GetString("LblGroupName", resourceCulture) ?? string.Empty;
    public static string LblGroupDescription => ResourceManager.GetString("LblGroupDescription", resourceCulture) ?? string.Empty;
    public static string LblParentGroup => ResourceManager.GetString("LblParentGroup", resourceCulture) ?? string.Empty;
    public static string ConfirmDeleteGroup => ResourceManager.GetString("ConfirmDeleteGroup", resourceCulture) ?? string.Empty;
    public static string StatusGroupCreated => ResourceManager.GetString("StatusGroupCreated", resourceCulture) ?? string.Empty;
    public static string StatusGroupDeleted => ResourceManager.GetString("StatusGroupDeleted", resourceCulture) ?? string.Empty;
    public static string ErrorCannotDeleteSystemGroup => ResourceManager.GetString("ErrorCannotDeleteSystemGroup", resourceCulture) ?? string.Empty;
    public static string ErrorGroupHasComputers => ResourceManager.GetString("ErrorGroupHasComputers", resourceCulture) ?? string.Empty;
    public static string DialogConfirm => ResourceManager.GetString("DialogConfirm", resourceCulture) ?? string.Empty;
    public static string DialogWarning => ResourceManager.GetString("DialogWarning", resourceCulture) ?? string.Empty;
    public static string DialogError => ResourceManager.GetString("DialogError", resourceCulture) ?? string.Empty;
    public static string DialogInfo => ResourceManager.GetString("DialogInfo", resourceCulture) ?? string.Empty;
    public static string BtnYes => ResourceManager.GetString("BtnYes", resourceCulture) ?? string.Empty;
    public static string BtnNo => ResourceManager.GetString("BtnNo", resourceCulture) ?? string.Empty;
    public static string BtnOk => ResourceManager.GetString("BtnOk", resourceCulture) ?? string.Empty;
    public static string BtnCancel => ResourceManager.GetString("BtnCancel", resourceCulture) ?? string.Empty;
    public static string ConfirmApproveUpdate => ResourceManager.GetString("ConfirmApproveUpdate", resourceCulture) ?? string.Empty;
    public static string ConfirmDeclineUpdate => ResourceManager.GetString("ConfirmDeclineUpdate", resourceCulture) ?? string.Empty;
    public static string ConfirmStartSync => ResourceManager.GetString("ConfirmStartSync", resourceCulture) ?? string.Empty;
    public static string ValidationRequired => ResourceManager.GetString("ValidationRequired", resourceCulture) ?? string.Empty;
    public static string ValidationInvalidFormat => ResourceManager.GetString("ValidationInvalidFormat", resourceCulture) ?? string.Empty;
    public static string ValidationInvalidHostname => ResourceManager.GetString("ValidationInvalidHostname", resourceCulture) ?? string.Empty;
    public static string ValidationInvalidPort => ResourceManager.GetString("ValidationInvalidPort", resourceCulture) ?? string.Empty;
    public static string ValidationMaxLength => ResourceManager.GetString("ValidationMaxLength", resourceCulture) ?? string.Empty;
    public static string ErrorUnauthorized => ResourceManager.GetString("ErrorUnauthorized", resourceCulture) ?? string.Empty;
    public static string ErrorNotAuthenticated => ResourceManager.GetString("ErrorNotAuthenticated", resourceCulture) ?? string.Empty;
    public static string RoleViewer => ResourceManager.GetString("RoleViewer", resourceCulture) ?? string.Empty;
    public static string RoleOperator => ResourceManager.GetString("RoleOperator", resourceCulture) ?? string.Empty;
    public static string RoleAdministrator => ResourceManager.GetString("RoleAdministrator", resourceCulture) ?? string.Empty;
    public static string LblCurrentUser => ResourceManager.GetString("LblCurrentUser", resourceCulture) ?? string.Empty;
    public static string LblCurrentRole => ResourceManager.GetString("LblCurrentRole", resourceCulture) ?? string.Empty;
    public static string AccessibilityHighContrast => ResourceManager.GetString("AccessibilityHighContrast", resourceCulture) ?? string.Empty;
    public static string AccessibilityNormalContrast => ResourceManager.GetString("AccessibilityNormalContrast", resourceCulture) ?? string.Empty;
    public static string AccessibilityReduceMotion => ResourceManager.GetString("AccessibilityReduceMotion", resourceCulture) ?? string.Empty;
    public static string AccessibilityFontScale => ResourceManager.GetString("AccessibilityFontScale", resourceCulture) ?? string.Empty;
    public static string BtnViewDetails => ResourceManager.GetString("BtnViewDetails", resourceCulture) ?? string.Empty;
    public static string LblUpdateId => ResourceManager.GetString("LblUpdateId", resourceCulture) ?? string.Empty;
    public static string LblSeverity => ResourceManager.GetString("LblSeverity", resourceCulture) ?? string.Empty;
    public static string LblReleaseDate => ResourceManager.GetString("LblReleaseDate", resourceCulture) ?? string.Empty;
    public static string LblFileSize => ResourceManager.GetString("LblFileSize", resourceCulture) ?? string.Empty;
    public static string LblProducts => ResourceManager.GetString("LblProducts", resourceCulture) ?? string.Empty;
    public static string LblCveIds => ResourceManager.GetString("LblCveIds", resourceCulture) ?? string.Empty;
    public static string LblSupersedes => ResourceManager.GetString("LblSupersedes", resourceCulture) ?? string.Empty;
    public static string LblSuperseded => ResourceManager.GetString("LblSuperseded", resourceCulture) ?? string.Empty;
    public static string LblSupersededBy => ResourceManager.GetString("LblSupersededBy", resourceCulture) ?? string.Empty;
    public static string LblRequiresReboot => ResourceManager.GetString("LblRequiresReboot", resourceCulture) ?? string.Empty;
    public static string ErrorConnectionFailed => ResourceManager.GetString("ErrorConnectionFailed", resourceCulture) ?? string.Empty;
    public static string ErrorTimeout => ResourceManager.GetString("ErrorTimeout", resourceCulture) ?? string.Empty;
    public static string ErrorScriptFailed => ResourceManager.GetString("ErrorScriptFailed", resourceCulture) ?? string.Empty;
    public static string ErrorRetryLimitExceeded => ResourceManager.GetString("ErrorRetryLimitExceeded", resourceCulture) ?? string.Empty;
    public static string ErrorCircuitBreakerOpen => ResourceManager.GetString("ErrorCircuitBreakerOpen", resourceCulture) ?? string.Empty;
}
